-- ===================================================================
-- GURBET KALEMLERİ: YORUM VE BEĞENİ SİSTEMİ
-- ===================================================================

-- Yorumlar tablosu
CREATE TABLE IF NOT EXISTS public.literary_work_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_id BIGINT NOT NULL REFERENCES public.literary_works(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  status TEXT DEFAULT 'approved' CHECK (status IN ('approved', 'pending', 'rejected'))
);

-- Beğeniler tablosu
CREATE TABLE IF NOT EXISTS public.literary_work_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_id BIGINT NOT NULL REFERENCES public.literary_works(id) ON DELETE CASCADE,
  user_identifier TEXT NOT NULL, -- IP adresi veya session ID
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(work_id, user_identifier)
);

-- Row Level Security
ALTER TABLE public.literary_work_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.literary_work_likes ENABLE ROW LEVEL SECURITY;

-- Yorum politikaları
CREATE POLICY "Herkes yorum görülebilir" 
ON public.literary_work_comments
FOR SELECT
TO public
USING (status = 'approved');

CREATE POLICY "Herkes yorum yazabilir"
ON public.literary_work_comments
FOR INSERT
TO public
WITH CHECK (true);

-- Like politikaları
CREATE POLICY "Herkes beğeni görebilir"
ON public.literary_work_likes
FOR SELECT
TO public
USING (true);

CREATE POLICY "Herkes beğeni yapabilir"
ON public.literary_work_likes
FOR INSERT
TO public
WITH CHECK (true);

-- İndeksler (performans için)
CREATE INDEX IF NOT EXISTS idx_comments_work_id ON public.literary_work_comments(work_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON public.literary_work_comments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_likes_work_id ON public.literary_work_likes(work_id);
