-- Create documents table
create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  file_url text not null,
  file_type text,
  file_size text,
  uploader_name text,
  profession_slug text not null,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected'))
);

-- Enable RLS
alter table public.documents enable row level security;

-- Policies
-- Everyone can read approved documents
create policy "Approved documents are viewable by everyone"
  on public.documents for select
  using (status = 'approved');

-- Admins (or everyone for now in this demo app context) can insert
-- In a real app, you might want to restrict this or use a function to upload
create policy "Anyone can upload documents"
  on public.documents for insert
  with check (true);

-- Only admins can update/delete (simulated by allowing all for now, or specific logic if auth was strict)
-- For this project, we've been using a loose policy for "admin" actions on the client side for simplicity, 
-- but let's allow all operations for now to ensure the admin panel works without complex auth setup.
create policy "Enable all access for all users"
  on public.documents for all
  using (true)
  with check (true);

-- Storage Bucket Policies (You need to create a bucket named 'documents' in Supabase Dashboard)
-- These are SQL commands to set up storage policies if the bucket exists
-- insert into storage.buckets (id, name) values ('documents', 'documents'); -- Optional: try to create bucket via SQL

-- Policy to allow public read of files in 'documents' bucket
-- create policy "Public Access"
--   on storage.objects for select
--   using ( bucket_id = 'documents' );

-- Policy to allow upload
-- create policy "Public Upload"
--   on storage.objects for insert
--   with check ( bucket_id = 'documents' );
