-- FAQs tablosunu oluştur
create table public.faqs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  profession_slug text not null, -- Hangi meslek için olduğu (örn: 'matematik-ogretmenligi')
  question text not null,
  answer text not null,
  display_order integer default 0 -- Sıralama için
);

-- RLS (Güvenlik) ayarları
alter table public.faqs enable row level security;

-- Herkes okuyabilir
create policy "Herkes SSS'leri okuyabilir"
on public.faqs
for select
to public
using (true);

-- Sadece adminler ekleyebilir/düzenleyebilir (Şimdilik geliştirme için herkese açık yapıyoruz, canlıda kısıtlanmalı)
create policy "Geliştirme: Herkes SSS ekleyebilir"
on public.faqs
for insert
to public
with check (true);

create policy "Geliştirme: Herkes SSS düzenleyebilir"
on public.faqs
for update
to public
using (true);

create policy "Geliştirme: Herkes SSS silebilir"
on public.faqs
for delete
to public
using (true);
