-- ===================================================================
-- GURBET KALEMLERI: SESLI ESER DINLEME KAYITLARI
-- ===================================================================

-- Dinleme kayitlari tablosu
CREATE TABLE IF NOT EXISTS public.literary_work_listens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_id BIGINT NOT NULL REFERENCES public.literary_works(id) ON DELETE CASCADE,
  user_identifier TEXT NOT NULL, -- IP adresi veya session ID
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Row Level Security
ALTER TABLE public.literary_work_listens ENABLE ROW LEVEL SECURITY;

-- Dinleme politikalari
CREATE POLICY "Herkes dinleme gorebilir"
ON public.literary_work_listens
FOR SELECT
TO public
USING (true);

CREATE POLICY "Herkes dinleme kaydi ekleyebilir"
ON public.literary_work_listens
FOR INSERT
TO public
WITH CHECK (true);

-- Indeksler (performans icin)
CREATE INDEX IF NOT EXISTS idx_listens_work_id ON public.literary_work_listens(work_id);
CREATE INDEX IF NOT EXISTS idx_listens_created_at ON public.literary_work_listens(created_at DESC);
