-- Experiences tablosunu oluştur
create table public.experiences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  name text,
  profession text not null,
  content text not null,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected'))
);

-- Row Level Security (RLS) aç
alter table public.experiences enable row level security;

-- Herkesin tecrübe paylaşabilmesi için INSERT izni ver (Anonim kullanıcılar dahil)
create policy "Herkes tecrübe paylaşabilir"
on public.experiences
for insert
to public
with check (true);

-- Sadece onaylanmış tecrübelerin herkes tarafından okunabilmesi için SELECT izni
-- (Şimdilik admin paneli olmadığı için bu kısmı yorum satırı yapıyorum veya basit tutuyorum)
-- create policy "Onaylanmış tecrübeler herkes tarafından görülebilir"
-- on public.experiences
-- for select
-- to public
-- using (status = 'approved');

-- Şimdilik geliştirme aşamasında verileri görebilmeniz için geçici olarak tüm okumalara izin verelim
-- (Canlıya geçerken bunu kaldırıp sadece 'approved' olanları göstereceğiz)
create policy "Geliştirme: Herkes her şeyi görebilir"
on public.experiences
for select
to public
using (true);
