-- ===================================================================
-- PART 2: ESERLERI TAM HALLERINE GÜNCELLE (IDs: 92, 65-71, 73)
-- ===================================================================

-- 92. Unut Diyorlar Sana (Turgay Almanya2) - ÇOK UZUN
UPDATE literary_works SET content = E'\'Unut\' diyorlar sana, \'güçlü ol, dik dur, sus...\'\nOysa taş değil bağrındaki, etten kemikten kafes.\nHangi ayet emreder acıyı yok saymayı?\nHangi peygamber ağlamadan geçti o dar kapıyı?\n\nSen \'Kabz\' halindeyim diyorsun, ruhum cenderede,\nSanma ki bu karanlık sadece senin pencerede.\nDön bak Kenan iline, Yusuf\'un babasına,\nHasretinden ak düşmedi mi Yakub\'un karasına?\n\nO \'Sabr-ı Cemil\'di ama gözleri görmez oldu,\nDemek ki özlemek, ne isyan ne de suçtu...\nVe hatırla o \'Hüzün Yılı\'nı, En Sevgili\'nin,\nGözünden yaş süzülürken o Rahmet Nebisi\'nin,\nTaif\'te taşlanırken kan dolan ayakkabısını...\n\'Unut\' demedi Rabbim, \'Unut ve devam et\'\nDedi ki: \'Senin göğsünü yarıp genişletmedik mi?\'\n\nDemek ki önce daralır, sonra genişler yürek,\nAcıyı \'yok etmek\' değil, acıyla pişmek gerek.\nSana \'Vatan bitti, hayaller bitti\' dedirten o sızı,\nBilal\'in de göğsündeydi terk ederken ıssızı.\nMedine\'de okurken o yanık beyitleri,\n\'Ah bir gece daha geçirsem Mekke vadisinde,\'\nDiye inlerken o \'Müezzinlerin Efendisi\',\nDavasına ihanet miydi sence bu hasretin sesi?\n\nŞimdi \'çarmıha gerili\' ruhun, arafın tam ortasında,\nAnnesiz, babasız, kolsuz kanatsız bir \'hiç\'likte.\nKorkma bu \'hiç\'likten, Mevlana da oradan geçti,\nVarlık iddiası biterse, tecelli orayı seçti.\n\nSen \'kendini yeniden doğurmaktan\' bahsediyorsun,\nDoğum sancısız olur mu? Elbette kanayacaksın.\nŞimdi \'Kabz\' ile sıkılan o mübarek canın,\n\'Bast\' ile ferahlayacak, yakındır zamanın.\nAğla kardeşim, ağla... Gözyaşın rahmettir,\nBu çektiğin ne zillet, ne de bir hezimettir.\nBu, Allah\'ın sevdiğine \'Bana sığın\' demesidir,\nVe o kırık kalbin, Arş\'ın en titrek sesidir.\nUnutma;\nKuyuya atılmasaydı Yusuf, Mısır\'a sultan olmazdı,\nGecenin en zifiri anı, sabahın tam kenarıydı...', tags = ARRAY['unutmak', 'kabz', 'bast', 'huzun'] WHERE id = 92;

-- 65. Ben Bir Göçmen Kızım (Tuba)
UPDATE literary_works SET content = E'Ben bir göçmen kızım. Hani hep anlatır ya neneler, dedeler zamanında şuradan göçtük de geldik diye. Evet ben o göçmen kızım.\nBir sırt çantasıyla çıktım evden. Ne ana aldım yanıma ne baba. Yanımda tanımadığım insanlar. Sanırsın kırk yıllık akraba.\n\nYalnız çıktım ama yalnız kalmadım. Ölümü göze aldım ama hiç korkmadım.\nTüm o tehlikelerden görünmez bir pelerinle geçtim sanki. İliklerime kadar dua hissettim.\nBir sabah ezanıyla veda ettim memleketime. Sonra suya bıraktım boğazımdaki düğümü.\nGöç acıtmadı da duyduğum hikayeler acıttı. Başım çatladı dayanamacağımı sandım o yolda ama o hikayeler kadar dayanılmaz değilmiş.\n\nŞimdi bana yaz bunları diyorlar. Ben ne yazsam nafile. Bir filmde izlesen senarist abartmış, biraz gerçeğe yakın yazsaymış der, hikayeyi sorgularsın ama kaderi sorgulayamazsın.\nÇünkü gün gibi gerçektir. Nasıl yazayım? Birileri atlarıyla yolumuzu açmasaydı ve bu uğurda ölmeseydi ben bugün bunu yazamazdım belki de.\nKısacık bir ömrün en çiçekli mevsimini bir zalimin zindanında geçirdiler. Kimi öldü, kimi sadece nefes alıyor.\nBiz dinlerken akletmekte zorlandık onlar yaşarken nasıl delirmedi inanamadık. İşin tuhaf yanı asla vazgeçmediler. Satmadılar... Aksine daha da kenetlendiler.\n\nBir tekerrürdü bu. Tarih yazılıyordu ama nice isimsiz kahramanlar bilinmiyordu. Çünkü onlar dünyayı düşünmüyordu. Abartı gibi değil mi?\nGörmesem, bilmesem, şahit olmasam ben de inanmakta zorlanırdım. Baksan hepsi normal insan.\nİki kol, iki bacak ama bu nasıl bir iman. Beni geçin. Ben gerçekten normal insan. Onların hakkı nasıl ödenecek?\nHaklarını helal ederler etmesine de Allah\'a dokunmaz mı bu zulüm? Ben bir göçmen kızım. Zulmün koynundan bilinmeze kaçtım.\n\nYeniden başlamaya, varsa ömrüm niyet ettim. Keşke verecek umutlarım olsaydı. Çünkü biliyorum artık buradan konuşması kolay.\nSessiz dualardan başka hiçbir şeyim yok. Sadece şu bilinsin. Burada gözler arkada, emek emek isyan var.', tags = ARRAY['goc', 'kadin', 'meric', 'zulum'] WHERE id = 65;

-- 66. Göçmen Kızlar (Yaşar)
UPDATE literary_works SET content = E'Göçmen kızlar... Evet, onların hikayesi şanla, gücün ta kendisiyle yazılır.\nDüşün bir kere, bu dünyada girişimci ruhun en derin kökleri, göçmenlerin yüreğinde atar.\nSosyoloji der ki; dünya üzerindeki en cesur adımlar, göçmenler tarafından atılır.\nTarihin çoğu devleti, şirketi ve medeniyeti göçmenlerin hayalleriyle kurulmuştur. Ve sen, bu yolculuğun bir parçasısın.\n\nBu göç, sadece bir yerden başka bir yere gitmek değil. Bu, bir inancın peşinden gitmek, bir hikmetin ardında yürümek demek.\nHer bir adım, seni yalnızca bir hedefe değil, aynı zamanda Allah\'ın sana sunduğu bir ödüle taşır.\nHani derler ya, \'hicret mükafatı.\' İşte o mükafatı, sadece inançları uğruna vatanını terk edenler kazanır.\nGöçün acısı, sonunda bir ödüle dönüşür. Hem bu dünyada, hem sonsuz hayatta... Allah, her adımda seninle ve bu vaadin gücü, her zaman yanında olacak.\n\nŞimdi, içindeki gücü hissediyor musun? Bu yolculuk hiç de kolay değil, ama unutma ki her adımda senin içindeki kahraman, daha da güçleniyor.\nHer daraldığında, her zorlandığında, Allah\'ın şu muazzam desteğini hatırla.\nBu vaadin gücü, her zaman yanında. O kadar güçlü bir güven var ki seni sarar; her adımda, her nefeste hissedebilirsin.\nÇünkü bu yolculuk, seni sadece bir hedefe değil, tüm zorlukların ötesine taşır.\nVe bir gün, o göçtüğün yer seni kabul ederken, sen de kendi topraklarında yetiştirdiğin o güçlü ruhu hayata geçireceksin.\nBunu hissedebilirsin. Bu dünyada ve ahirette seni bekleyen ödüller, her adımda daha da yakın olacak.\nUnutma, sen bir göçmen kızısın, ama asıl önemli olan, senin içinde bir kahraman olduğudur.\nİçindeki güç, her geçen gün büyüyor ve sen her adımda ona daha yakınsın.', tags = ARRAY['goc', 'guc', 'inanc'] WHERE id = 66;

-- 67. Kamp Psikolojisi (Tuba)
UPDATE literary_works SET content = E'Kısa bir kamp psikolojisi analizi... Güçlü hissediyorsun, yalnız değilsin, önünde açık bir yol var. Umudu iliklerine kadar hissediyorsun.\nEmekleri gördükçe hayretler içinde kalıyorsun... İç savaşlar yaşıyorsun. Gel-gitler yaşıyorsun.\n\nKimsenin duymadığı yanlarını sen dinliyorsun. Sebepsizce ağlamak istiyorsun.\nBazen ağlayamıyorsun, bazen de ağlamanı durduramıyorsun. Tabloya dışarıdan bakmakta zorlanıyorsun. İçeride bir akış var ve fark etmiyorsun. Durmakta zorlanıyorsun.\nBir sürü insanı aramak istiyorsun ama kimse zarar görmesin istiyorsun. Aslında ne çok seviliyormuşum diyorsun.\nBir yandan da yine ayıklıyorsun insanları ki bu da alışık olduğun bir durum.\n\nDerken odanın kapısı çalıyor ve karşı odadan hadi çay içelim deniyor ve dünyan yarım saatliğine yine güzelleşiveriyor...', tags = ARRAY['kamp', 'psikoloji', 'dostluk'] WHERE id = 67;

-- 68. Kadın Olmak (Tuba)
UPDATE literary_works SET content = E'Kadın olmak çok güzeldir aslında. İçinde çocuk neşesi, kalbinde kelebekler, ruhunda dünyanın bütün renkleri vardır kadının.\nÜç kadın bir araya gelelim mesela. Hani matah bir şey değil ama bir dedikodu döner sabaha kadar sürer gider.\nO muhabbete üç ağlama seansı iki göbek havası, bir de terapi seansı sığdırırız.\n\nBir evde kadın varsa neşe vardır, düzen vardır, dağınıklığın bile bir pozitif enerjisi vardır.\nSevmesini biliriz bir kere. Nefretin kitabını yazarız. Öfkede kaç kurtar kendini.\nAzim mi, kırılganlık mı, duygusallık mı, cesaret mi... Öyle üç aşağı beş yukarı değil ne hissedersek tam hissederiz.\nHele ki kadının toplumda sahip olduğu rolleri tek tek açsam hepsinden ışık saçılır etrafa.\nEminim zorluklarından birçok kişi hakkını vere vere bahsedecektir. Ben bugün kız neşesinden bakmak istedim bize.\nDünya Kadınlar Günümüz kutlu olsun', tags = ARRAY['kadin', 'guc', 'nese'] WHERE id = 68;

-- 69. Benim Annem (Tuba)
UPDATE literary_works SET content = E'Benim annem beni hep yolcu etti.\nDefalarca ameliyathane kapısından el salladım ona.\nNe kadar zordur evladını bir bilinmeze göndermek diye düşünürdüm hep.\nSonra bir gün büyüdüm.\nKoca kız oldum.\nKapıya polis geldi.\nAnnem yine yolcu etti beni, sıcak çorbasını içirmeyi ihmal etmeden.\n\nSonra daha da büyüdüm.\nBen bu sefer daha büyük bir bilinmeze gidiyorum anne dedim. Hakkını helal et.\nBenim gibi binler, on binler var anne dedim.\nNasıl yapıyordu?\nİnsanın kendisi için endişelenmesi kolay.\nEvlat için her seferinde buna nasıl dayanıyordu?\n\nSen de tek değilsin annem.\nNice anne evladından ayrı, nicesi de kavuşmayı hayal bile edemiyor.\nAnne olmak başlı başına bir imtihandı belli ki.\nBu da göçmen bir kızdan annesine mektup olsun...', tags = ARRAY['anne', 'veda', 'gurbet'] WHERE id = 69;

-- 70. Bir Bebeğin Göç Hikayesi (Tuba)
UPDATE literary_works SET content = E'Bir bebeğin göç hikayesini dinlediniz mi hiç?\nMesela bir seferlik konuşma hakkı olsa ve yolculuğunu anlatsa... Dinlemeye gücünüz var mı? İçtiği şurubun tadını söylese mesela.\nSoğuğu, karanlığı, annesinin kalp atışını anlatsa...\nTek iletişim aracı olan ağlamasının nasıl hayati bir risk taşıdığını anlatsa...\n\nBir zulme binlerce kişi maruz kalınca o zulüm normalleşmiyor. Hâlâ çok ağır, hâlâ haykırmaya değer.\nŞimdi bebeklerin anne karnındaki travmalarından bahsediyorlar.\nZulmün ortasında doğan bebekler, travmanın tanımını baştan yazıyor.\n\nBirleşmiş Milletler kampında gördüğüm bebeklerle bol bol oynamak istedim. Her şey o kadar ciddiydi ki... Onların dünyası oyundan ibaret olmalıyken benimle aynı imtihanı yaşıyor olamazlardı.\nÖmer bebek vardı mesela. Saçları kirpi bebek. Ciddi. Sanırsın kamptan kaçış planı yapıyor. Fındık, ne bu ciddiyet?\nHerkesle oynar Ömer. Baktı, beğenmiyor; etinden et koparcasına ağlar. Sen nasıl geldin o yolu, mübarek?\nYoksa senin için mi açıldı kapılar? Bize moral için mi buradasın yoksa?\n\nBir de soruları cevapsız kalan çocuklar vardı. Anlıyorlar, hissediyorlar ama şaşkın ve sessizler.\nYere sek sek çizdim, belki bir an için unuturlar nerede olduklarını da sadece çocuk olmayı hatırlarlar diye.\nHiçbir çocuğun bu kadar çabuk büyümesini istemezdim.\nCezaevinde doğmamalılar mesela...\nDoğdukları gün babaları tutuklanmamalı; cezaevini babalarının iş yeri sanmamalılar mesela...\nOnlara adil olmayı öğretirken, adaletsizliğin muhatabı olmamalılar...', tags = ARRAY['bebek', 'goc', 'kamp'] WHERE id = 70;

-- 71. Baba Deyince (Tuba) - ÇOK UZUN
UPDATE literary_works SET content = E'Baba deyince ne geliyor aklınıza?\nBelki güç, belki bir çınar ağacı, belki evin reisi…\nBenim aklıma orada olduğunu bildiğim bir sığınak geliyor.\nÇocuk kalabildiğim bir liman\nBüyürken yaslanabildiğim dağ,\nKüçükken evden kaçmışım biliyor musunuz?\nBabam işe, ben babamın peşine. Sokaklarda babamı arıyorum.\nSonra iki tane kızın elinden alıvermış ablam beni.\nYedi yaşımda hastanede yatarken baba diye ağlıyormuşum anneme.\nBen annem olsam çok gıcık olurdum bana.\n\nDeyimler ve baba sözlerim vardır mesela\n\'Kat-i-yen\' demişse babam orada işimiz yaş.\nAkşama \'spesiyal\' varsa maklube için hazır olun.\nBir soru sorarsın cevabı babamda değil babamın kitaplıkta gösterdiği bir kitaptadır.\nEğlencelidir bendeki baba kavramı.\nMesela siz hiç sucuklu mercimek çorbası yaptınız mı?\nYa da bir buçuk metrelik kardan adamı siniyle dördüncü kata çıkardınız mı?\n\nHayatımda kendimi en çaresiz hissettiğim andır babamın cezaevine girişi\nİçimde bununla baş edebilecek bir data yoktu. Sistemde kayıtlı bir duygu bulunamadı yani.\nBen de baba rolüne girdim evde.\nAnnem iyi mi, \'çocuklara\' para yetiyor mu, avukatla toplantı ne zaman… Bu \'hissetmemi\' kolaylaştırdı.\n\nSonra babam çıktı. Dedim ki baba müsadenle ben sana yaslanacağım bir süre. Sadece kendim olacağım.\nEvde koridorda yürüyen babam mıydı? Gerçekten burada mıydı?\nBunu şöyle anlatayım. Bir gün komşumuzun eşi tahliye oldu ve küçük kızına birden karşısına çıkarak sürpriz yaptı.. Bu küçük kız bana olayı nasıl anlattı biliyor musunuz? Abla robot sandım gerçekmiş dedi.\nGerçekmiş..\nBabam bana güvenmeseydi ben kendime güvenemezdim belki de. Şimdi her adımımda izleri var hayatımda.', tags = ARRAY['baba', 'guven', 'hapis'] WHERE id = 71;

-- 73. Sıfırdan Başlamak (Tuba) - ÇOK UZUN
UPDATE literary_works SET content = E'Yeni bir başlangıç yapmakla sıfırdan başlamak arasında kocaman bir fark vardır.\nHiçbirimiz sıfır noktasında değiliz. Bugünlere getirdiğimiz, yetiştirdiğimiz karakterimizin şimdi en büyük meyvesini yiyoruz.\nMesela neden pes etmedin, neden tanımadığın insanlara kol kanar gerdin, neden olduğun yerde efendiliğin ve hanımefendiliğinle dikkat çekebiliyorsun hâla, neden beş yüz metreden öteden güzel ahlakın anlaşılıyor, neden her ne meslek yaparsan yap insanlar sana gözü kapalı güveniyor?\n\nÇünkü sıfır değilsin. Yeniden başlıyorsun. Ben öğretmenim mesela. Hayatta kendimi en yeterli hissettiğim andır ders anlattığım o 40 dakika.\nHayır değilsin dediler. Peki dedim. O zaman mesleğimin yasını tutar yeniden başlarım. Bilmiyorum nasibimde ne var.\nHatta heyecan ve merakla bekliyorum. Tabii ki benim de hayallerimin arasında mülteci olmak yoktu ama Avrupa da yoktu, yeni bir dil de yoktu, kendi sınırlarımı aşmak da, konfor alanımın altını üstüne getirmek de yoktu.\n\nBazen rüyamda Türkiye\'deki odamda buluyorum kendimi. Yani en güvende hissettiğim yerde.\nSonra ya kapı çalarsa, ya gelirlerse ürpertisi ve ailem çok üzülecek hissi... Bütün bunlar hücum ederken uyanıyorum.\nOrada değilsin, güvendesin, etrafında şahane insanlar var ve evet yapabiliyorsun, devam edebiliyorsun... Kendime yazdığım notlardan bir tirat sunuyorum bir anda.\n\nSıfır olsaydık ayakta duramazdık. Kampta arkadaşlarla bir masada çay içiypruz mesela.\nFizik profesöründen, hakimine, matematik dehasından tarihçisine, mimarından türkçecisine masa kaynıyor. Hepsine hayranlıkla baktım. Evet hepimiz mülteciydik ama birikimlerimiz bambaşkaydı.\nHer biriyle ettiğim muhabbetin lezzeti ayrıydı. Onlar hâla gururu hakediyor.\nÇünkü onlar zamanında sadece vezir olmakla kalmayıp insanlığın özün0 yaşayan ve yaşatanlardı.\nHepsiyle gurur duydum.\nKabul edelim sıfır bu durumdan çok uzak bir rakam.', tags = ARRAY['baslangic', 'umut', 'multeci'] WHERE id = 73;

-- Kontrol
SELECT COUNT(*) as "güncellenen" FROM literary_works WHERE id IN (92,65,66,67,68,69,70,71,73);
