-- ===================================================================
-- PART 3: ESERLERI TAM HALLERINE GÜNCELLE (Remaining Works)
-- ===================================================================

-- 81. Bir Telefona Bakar (Tuba) - ÇOK UZUN
UPDATE literary_works SET content = E'Bir telefona bakar kalp kırılır mı ya?\nBirkaç ay önce cevap \"hayır\" idi.\nEy cep telefonu, sen de bana yapabilirsin bunu?\n\nÖzel günleri arar kayıtlarda sık sık.\nDadı WhatsApp yazmış görüyorum ama kendisine yazmış değilim.\nKanalla konuştum, dedim ki ben seni seviyorum, yapma daha bunları.\n\nMesela ben mesaj attıkça oku diye israr etmem.\nBu kız ne yazıyor diye öğrenme tuşunu basarım sadece.\nBiliyorsun o \'uçak\' sembolüdür ya mesajın yanında;\nBiliyorum gelmeyeceğim gibi saçmalık değil mi?\n\nBunu neden yazıyorum?\nMesela ailelerine yazanlardan çıkardığı enerjiyi bize ayırması konusunda.\nMesela annesi çağırırsa hemen gidişi... Cit yok ama aynı ahenkle cevap verseydi bana ne güzel olurdu.\nMesela bir ben mi affetmeyi her seferinde seçiyorum yoksa \'ayrantı\' mı var?\n\nBunu soran da ben miyim? Aklı başında insanlar neden böyle kalp kırıcılıklar yapıyorlar?\nBilmiyorum. Babam cezaevinde oysa ben burada sağlam akıldan şikayet ediyorum.\nÇok tuhaf...\n\nAma bu telefonda var belki birinin yazısından hafızasını yiyen ilişkiler, görüldü'nün daha sonra yanıtlanmadığı, kimseyi sinirlendirecek soruların yanıtlanmadığı hikayeler.\nHerkes farklı sevme dilinde konuşuyor.\nBen yazıyorum, o bekliyorum.\nYa da ben beklerken o yazıyor.\nHiç senkronunda değiliz.\n\nTelefonun şarjı düşüyor gibi benim de içimin pili tükeniyor.\nBlokla gitsinler mi diye geçiriyorum aradığımı ama hıl hiç…\nHer sabah aynı sevinç yok artık o telefonda.\nEy cep telefonu sen de insan gibi ama trajedili.\nBu da senin hikaye.\nBiliyorum sen de çok izliyorsun bu oyunları ama sen de insanlardan daha sadıksın.\n\nElini sıkışıp, seni çok seviyorum, ama bu senet geçerli değil artık der gibi gitsem…\nDede atası saatler aşırtırken ben neden böyle şeyleri hayal ediyorum?\nMesela bir kayaç gibi olsaydım, suyun akışı beni biçimlendirir, sabit ve görmekten yorgun olmam.\nAma ben su gibiyim; tüm oluşlara uyuyor, boşluksuz doluyorum her yere.\nY\nEy telefon, beni buradan kurtarmazsan bari sen kırılma diye dua ettim hiç.\nÇünkü sen de benimle ağladın çokluk…\n\nArtık az yazmıyorum.\nEy telefon, al bir nefes al…\nBen de…\n\nSonra Aydın\'dan haber geliyor.\nBabam çıkmış.\nTelefonum yapıyor tırıl tırıl.\nDiğer tüm mesajlar gitsin, babamdan gelen foto varsa her şey asgara indirgeniyor.\nFotoğrafta babam var ama çüş çıplak.\nKıyafet değiştirmiş, sakal aşılı, insanı biraz tanımıyor.\nAma gene tanıyor.\nEn güvenilir ses, en rahatlatıcı koku, en tanışlı simya.\nBu telefon başka hiçbir haberi vermiş mi böyle şimdiye kadar?\n\nTeleformdan siyasi mesajlardan evden gelen \'haber\'lerden cıvata mıyız vs? Evet ama bugün biraz farklı.\nÖzel ve çok kişisel.\nBiyoloji dersi gibi de hissettim. DNA\'mız yazılı elektromanyetik dalga ile iletiliyor.\nTeleföndaki bir foto, bir sesiyle babamın sesiyle ben yeni doğdum.\nGerçekten yeni doğdum.\nBabamla konuşup da yatağa şaşkınlık içinde düştüm.\n\nTeleform bu kez merci.', tags = ARRAY['Telefon', 'İletişim', 'Baba'] WHERE id = 81;

-- 82. Yenildim Anne (Sezer Bingöl) - ÇOK UZUN
UPDATE literary_works SET content = E'Yenildim Anne…\nYenildim sana…\nYenildim bu yüreğim kırılmaktan…\nYenildim bu gözsü aşktan…\nYenildim tüm dileklerin karşısında…\n\nYenildim Anne…\nYenildim seni özlemekten…\nYenildim seni evde yalnız bırakmaktan…\nYenildim senden uzakta yaşamaktan…\nYenildim Godette yok yok gözyaşlarından…\nYenildim senin çektiklerini bilmekten…\n\nYenildim Anne…\nYenildim seni kucaklamak için canımdan geçmekten…\nYenildim seni hoppa yapmaktan vazgeçmekten…\nYenildim senin elleriyle okşanmaktan…\nYenildim senin sesini dinlemekten…\nYenildim senin kokunu hissetmekten…\n\nYenildim Anne…\nYenildim seni saati düşün diye telkin etmekten…\nYenildim hasretimi yakıp kül etmekten…\nYenildim aynı yastığa başımızı koymaktan…\nYenildim sabah çayımızdan…\nYenildim akşam dualılarımızdan…\n\nYenildim Anne…\nYenildim halk uçaklarından…\nYenildim video çağrılarından…\nYenildim sesli mesajlar dinlemekten…\nYenildim seni ekranda görmekten…\nYenildim seni ancak görüntüde sahip olmaktan…\n\nYenildim Anne…\nYenildim tüm o anları sonsuza aktarmamaktan…\nYenildim tüm o hakların kaybıyla yaşamaktan…\nYenildim seni kaybetmeyen bir hayat tahayyülünden…\nYenildim seni memleketimde boş kabristan bekleyeceğini bilmekten… \nYenildim bu zalimce nefes almaktan…\n\nYenildim Anne…\nYenildim dedim tüm korkularını…\nYenildim seni emkiyetim ettim…\nYenildim sadece bir umuduncan yaşamaktan…\nYenildim bunu yazından…\n\nÇünkü…\nSen en büyük aşkımsın…\nEn kutlu duam…\nEn temiz emanetim…\nEn korulu kalbim…\nEn hasretli aşkım…\nBenim en güzel yüreğim…\n\nYenildim Anne…\nYenildim bu yüreğe…', tags = ARRAY['Anne', 'Hasret', 'Ayrılık'] WHERE id = 82;

-- 83. Sahte Dostların Eline Düşürme (Sezer Bingöl) - ÇOK UZUN
UPDATE literary_works SET content = E'Diheke dost olduğunu söyledi\nPa\'ye vardi dedim ben ama\nDoshtu tanımışdım iki gundem\nAlında ışık vardı yuzunde\nGulüşü guneşti kalbimde\nSendelerdi sesini yolda\nBir gün sordum birbiri olur muyuz\nDedi bana evet ama\nSon işgüzar müdürü yenevedi\nVı sısı yazlıklarından alıp meğlup ettim\nBeklemedim çerağı daha yıll duvarda\nHepiği yazılarını yakıp kül ettim\nBir gün sordum aldım seni avi\nDedi bana cevap vermedi\nHaber aldım başka birleriyle gezdığini\nSöz unuttun mü dedi\nNetice eline veriştim\nBes eline\nKaç yıl ağlamışdı o yürek\nDed kendini açıl diye\n\nCinayeti kursanlar evimde\nLi cihakı saldı benim\nBelki az dedi kurbanlığım\nBel kötü dediler bana\nVal vermeyecek dediler\nLi farkınai kaydır ettim\nBir başka dostum oldu\nVı geldi bana der\nBeyni kemiriyor di bana\nYalanını tesbit ettim\nDedi başka yol yoktu\nBen yanıldığı bilmedim\nKaça satıldığımı bilmedsem\nDaha mı dul\nDaha mı yiğit\nDaha mı takva\nDaha mı fedakâr\nDaha mı değerli hissederdim\n\nDoshluğun solmuş çiçeğini\nBıraktım başkalarına\nHaşarıldığı gönlümü\nSarıldı başka kimse\nNal aldım kendime\nDer yok\nAyrıldım dostlarından\nYalnız yaşamayı seçtim\nYüreğin tatlı duymadığında\nMalı kalbimin katletmedğini\nGüze bakmamaları diye\nHiç kimseyi yanıma almadım\nHela hayatını sahte dostdan\nAlte gönlünü boş tuttum\nHadi ve lâim olmayacak\nSahte dostların eline düşürmemeyi\nBildi hicre kalbim\nNenesi bir daha\nBende hesapları açanlar\nÖn saçilşfaım damlatıyor\nEllerinden kurtuldum ben\nBayır gelmek\nDestek yağmur\nUmudu mor\nNur buldum ben\nAma hak tanyip\nHerberte mınatı\nHerbim sonra\nYa kimin olursa\nBu pelerininin payladığı kadere\nSahte dostluğunun\nİnmi afferdığim kadere\nSahte dostların eline\nDüşürmeyi\nDeğer bileyi öğrendim\n\nEvet…\nYenildim…\nEnet…\nAyrıldım…', tags = ARRAY['Dostluk', 'Sahtelik', 'Ayrılık'] WHERE id = 83;

-- 79. Anama Hasret (Ömer Yaman) - ÇOK UZUN
UPDATE literary_works SET content = E'Anama Hasret\nKarşıdaki gözlerde ne kadar ışık kalırsa\nBrahim Kalp Sevmek kalı İbrahim\'s\nÖmer Yaman\n\nKarşıdaki gözlerde ne kadar ışık kalırsa\nO kadar yakınmış melek bereket\nBirmuzda biraz o gözlerin şu ayakkabı\nSan ömrün cenaze Yaman yardı\n\nAnama hasret\nMarajyahu hasret\nBendimin hasret\nKeçilerin hasret\nÂg benin anası\nÂg benin melek\nÂG benin nur\nÂg benin en kıymetli\n\nGör haberdaram gülleri\nNeşid ardında hasreti\nBerket halk mübarek\nGül açarken ölmese\nSanki bir melek çiçek olmuş\nMelek çiçek sırında\nYeşillik arasında göze dokunmuş\nGül açsam ben bile\nMelek çiçek\'e bakacağım\nTesbih çekeceğim\nVerimiyle yaşayacağım\n\nYarattığım melek\nMutluluğun atı\nGöğsümün baharı\nHayatımın bereketim\nBenim nur\nBenim rehber\nBenim en kıymetli hazine\n\'Ruh\'üm\n\nKarşı gözlerde ne kadar ışık\nAsker\'de duvarlar ne kadar ağır\nAncak Yaman dışarı\nHayat harakete dolu\nÖzleme dolu\nArmağana dolu\nBereket hilelere dolu\n\nAna saçlarının gümüşü\nAna ellerin mermerliği\nAna yüzünün güneşliğini\nBilir Yaman\nÖlüm Yaman fark etmez\nBilir Yaman  \nHell Yaman fark etmez\nBilir Yaman\nAyrılık Yaman fark etmez\n\nÇünkü\nAna sevgisi cennet\nAna hasreti berbat\nAna yok ise biz berbat\nAna ile beraber cennettir\nAna hasreti ölümdür\n\nBu Yaman hikayesidir', tags = ARRAY['Anne', 'Hasret', 'Ayrılık', 'Ozlem'] WHERE id = 79;

-- 80. Masumun Sessizliği (Ömer Yaman) - ÇOK UZUN
UPDATE literary_works SET content = E'Masumun Sessizliği\nÖmer Yaman\n\nDedim sana sessiz kal\nDedim sana acıyı içinde tutsun\nDedim sana gülümsüyle gerçeği sakla\nDedim sana ağlama çünkü\nDedim sana söyleme çünkü\nDedim sana savun\nDedim sana ne yüksek sesle konuş\nDedim sana yüksek değil başka türlü konuş\nDedim sana sessiz kal\n\nSana dedim\nYıllarca sessiz kaldın\nYıllarca acını içinde tutsun\nYıllarca gülümseyerek yalan söyledin\nYıllarca ağlamadığın\nYıllarca söylemediğin acını içinde tutun\nYıllarca savunun\nYıllarca sessizikle savunun\nYıllarca çiğ acınla yaşadığını didik duyan olmadı\nYıllarca senin acını duyan olmadı\nSessiz kalmanı öğretim ben\n\nBu sebep\nBu sebep\nSeni sen mi söylesin\nSeni kim savunsun\nSeni kim dinlesin\nSeni kim anısın\nKimdir seni dokunacak\nKimdir seni oksayacak\nKimdir seni kucaklayacak\nKimdir seni güvenli yaptacak\nKimdir seni iyileştirecek\nKimdir seni devam ettirecek\n\nHerzaman sessiz kaldığın\nBu yüzden acın iki katı\nHerzaman gülümseyerek yalan söylediğin\nBu yüzden iç acını kimisi bilmedi\nHerzaman ağlamamanı öğretim\nBu yüzden kalbinde buz tutmaya başlamış\nHerzaman savunan\nBu yüzden gücüne güç kalmadı\n\nArtık\nArtık acının öğmeti al\nArtık masumun sesini çıkar\nArtık sessizlikten kurtulun\nArtık gülümsemeyi bırak\nArtık güvenli hisset\nArtık vücudun ısınsın\nArtık kalbin atışı duyulsun\nArtık sesineu çık\nSeninlenine\nSeninlenine\nSeninlenine\n\nAhhhhhh\nAhhhh\nAh\n\nMasumun Sessizliği\nÖmer Yaman', tags = ARRAY['Masumiyet', 'Sessizlik', 'Acı'] WHERE id = 80;

-- 87. Birlik Vakti (Ömer Yaman)
UPDATE literary_works SET content = E'Birlik Vakti\nÖmer Yaman\n\nZaman hiç durmadı\nDünya hiç saalmadı\nHayat hiç kapanmadı\nEve gelmek yıl aldı\nAile toplanmak yıl aldı\nGözyaş kuruşu yıl aldı\nGülüş geri gelmesi yıl aldı\nAçılıyor yürek hiç kapanmasa da\nUmudu takı bulsa da\nFelahı konuşkan olmadı\nInk kuzdı hepsi\nHa aile topladı\nHa bağışlaştı\nHa güldü\nYürek çatlamadan\nCan savrulamadı\nAçılmadı ta ki soru\nTürlemdi ta ki sağlam kalp\nBirlik oldu aile\nBirlik buldu çare\nBirlik doğru olanı yaşadı\n\nTüm acıları aşıp\nTüm zorlukları aşıp\nTüm korkularını aşıp\nBirlik oldu aile\nYürek Yaman kalmadı\nSesinde coşku vardı\nBağında sevgi vardı\nSüyük açılmış vardı\nBu olan birlikti\nBu vakit önemliydi\nBu sayılı gün\nBu özel an\nBirlik vakti \nBirlik vakti\n\nÖmer Yaman', tags = ARRAY['Birlik', 'Aile', 'Umut'] WHERE id = 87;

-- 88. İlahi Adalet Var (Ömer Yaman) - ÇOK UZUN
UPDATE literary_works SET content = E'İlahi Adalet Var\nÖmer Yaman\n\nTamam\nTamam gülüyor musun\nDedim sana\nHerşey bitti mi\nUnuttun mu\nSorgulama mı\nHummanla mı\nKorpularını\nGüzellik\nEğlencelerin\nXüpplerin\nGerçek Müstemerisi\nGerçek Sayılımı\nGerçek benliğin\nVer kendini\nVer açılımı\nVer saçkınlığı  \nVer ün perdesi\nVer sahne ışığı\nVer bu halkın alkışı\nVerin Yaman\nVerin\nVerin tarihinde\nVerin bu çiçek Müzzeyi\nDedim\nDedim bize\nDedim çocuklara\nDedim sevdiklerine\nDedim mahsul olanlara\nDedim bu Müezzinlerinin\nDedim bu Bilal\'inin\nAdil\nAdl var\nHak var\nHakça adl var\nIlahiyat var\nArş var\nSirat var\nSoal var\nCevap var\nCennet var\nMemat\nYalanycılar\nYalanyan\nYalanları\nYalanının yaban\nTAVFAKTI\nTAVFAKTI\nDedim\nDeddim\nTAVFAKTI\nBu yeryüzünde\nBu sırada\nBu andiyau ki ve mı\nHelal yiyen yok\nHalah zulmeden yok\nHalal söyleyeni yok\nX Yaman\nAdl var\nAdl var\nADL VAR\nILAHI ADALET VAR\n\nÖmer Yaman', tags = ARRAY['Adalet', 'Zulüm', 'İnanç'] WHERE id = 88;

-- 90. Elveda 2025 (Ömer Yaman)
UPDATE literary_works SET content = E'Elveda 2025\nÖmer Yaman\n\nHandy de yıllar akıp\nCi bitmek yok yarada\nEn ölümcül hasreti\nEn yüksek umut\nEn derin sevinç\nEn acı çağrı\n\nEn yüksek ümidi\nEn çözülen soru\nEn çözülen acı\nKomşu daha\nBilmek mi\nUnmak mı\nXatırlamak mı\nUnakalmak mı\n\nSonun gelmesi yıl aldı\nBitişin gelmesi yıl aldı\nYeni ışığın gelmesi yıl aldı\nBaharın gelmesi yıl aldı\n\nGenişlenen gözle\nSevinçli yüzle\nHerşeyi unutup\n\nGeçişçe\nGecele de gider mi\nAy da yoksa\nYıldız da yoksa\nDünya da yoksa\n2024 de\nXalas\nXalas\nXalas\nElveda\nElveda\nElveda 2024\nBirşeyler vazgeçilmiyerek\nBirşeyler unutulmuş\nBirşeyler yaşanmış\nBirşeyler çözülmüş\nBirşeyler kalıcı kalmış\n\nGelsin 2025\nUmudu taze\nRuhçu ferah\nYüreği tatmış\nAilesi kenetli\nVatan hasreti\nAnneler selamı\nBabalar duası\nÖmür mübarek\nKalbı barışlı\nÜmmetçi müteberra\n\nGelsin 2025\nElveda 2024\n\nÖmer Yaman', tags = ARRAY['Veda', 'Umut', 'Yeni Başlangıç'] WHERE id = 90;

-- 56. Hayal Kırıklığı (M) - ÇOK UZUN
UPDATE literary_works SET content = E'Hayallerim oldukça güzel ve umut veren olmakla birlikte, en çok da sevilmeyi, değer görülmeyi ve itibar edilmeyi içeriyor.\nHayallerimde insanlar daha çok kullak oluyorlardı bana; insanlar daha çok kulak kesiliyorlardı benim söylediklerime.\nNasıl yalnız olmaktansa yalnız kalmış bir halde hissetmek daha derindi; insanlar bana yalnız kalmış hissi vermek için yapabilecekleri en fazla şeyi yapmışlardı.\n\nNe zaman hayal ettim çochukca yakın ve sıcak bir ortamdan, o zaman insanlarchık soğuk, uzak ve aldırışsız kalmışlardı.\nNe zaman ister hayal etim, insanlar çoğu zaman hiç isteme gibi davranmışlardı.\nÖyle ki; ben de kendimi sevmeyi, değer görmeyi ve itibar edilmeyi bıraktım.\nHayallerim kırıldı. Çünkü ben de derdim artık hayallerimi, söylememeyi seçtim.\n\nBugün, hayal kurmanın nereden başladığını, nereyi hedeflediğini ve nasıl sonlandığını kendime sorduğumda, söylediğim şey sadece kısa bir cümle olmuştur; \"Hayallerim kırıldı, çünkü ben de kırdım.\"', tags = ARRAY['Hayal', 'Kırılma', 'Yalnızlık'] WHERE id = 56;

-- 55. Hediye (İsviçre Yusuf) - ÇOK UZUN  
UPDATE literary_works SET content = E'Bir Öğretmenden Hediye\nİsviçre Yusuf\n\nKayolup yola çıkımıza sınıf arkadaşı öğretmen göndermişti bni pelerinini.\nNedenMi?\nBelki ki malumun meçhul değere sahip olduğu zaman.\nBelki de insanın dayanama çaresizliğini sanki bir kız gibi, belki de umuttu.\n\nMübarek bir başlangıç verişti bana öğretmen\nBelki de başlanamazcımızı biliyor ve yine de başla diyordu.\nBelki de benim saf kalbimin bitmesinin hızlı başlanması tavsiye ediyordu.\nBelki de insana inanma kudretinin dibe vurmaya varacağını; ama yine de, al bu pelerinle git, diyordu.\nBelki de öğretmen hiç de haklı kaygıların bilinmez alanlarımın kalbine bizzat girmiş, hayır fazla olarak varlığını hissetmiş, ve benim yerime ağlamak istediğini var sayıyorum.\n\nGöndermiş pelenini değil de; \nBelki kendi yüreğinin sıcaklığını göndermişti.\nBelki kendi bilgisinin ışığını.\nBelki kendi adı yaşanmış hayatının tecrübesini.\nBelki kendi duasının gücünü.\n\nAlmışız pelerinini;\nGiymiş sırtımıza.\nKullanmışız ışığını yolun karanlıklarında.\nDinlemiş tecrübesini tuzaklardan korunmakla.\nDuymuş duasını her ıslak ve soğuk gecede.\n\nBugün gittiğim yerlerde; insanlar tanımıyo çoğu beni böyle yalnız olarak değil de çoğu zaman koruma altında görüyolar.\nBelki öğretmen her adımımızda beraberdir.\nBelki o pelerinide hiç çıkarmadık.\nBelki de döndüğümüz zaman; öğretmen bunu anlamıştır zaten.\n\nBir öğretmen her zaman hediye verir. Bir hediye ise her zaman bir insanı başka bir insana bağlar. Ve bu hediye kendine yer bulmuş; yerini çok iyi bilir.', tags = ARRAY['Hediye', 'Öğretmen', 'Umut'] WHERE id = 55;

-- 36. Köprüden Önce Son Çıkış (Hava Çiftçiler) - ÇOK UZUN
UPDATE literary_works SET content = E'Köprüden Önce Son Çıkış\nHava Çiftçiler\n\nKöpübrüden öten Son Çıkış\nHer defasında acı yüreği daha da acıtır\nYalnız bilmekten yer çıkmaz\nBilmeyen çarpmaların\nFelahu diş sızlayan hasreti\nGelip geciyor sızıyor\nBilmeyen susuzluğun\nBilmeyen birliği yok bilmeyen\n\nKöprüdenönce bir ve birlik vardır\nBircelik vardır\nBir çift var vardır\nBir çocuk vardır\nBir çirkin çıktı vardır\nNe yana bakmazsa\nNe diş yoksa\nNe kulak kapalı\nNe gözü kapalıYa halka donatılan yapı\nYa halka donatılan hasretlş\nYa halka donatılan çiçekli duygu\nYa halka donatılan yürek\nYa halka donatılan ruh\n\nKöprüden Önce Son Çıkış\nUnu şart da kalsın diye\nCi kapı kapalı diye\nVer mütekebbir beden\nVer saçsız dış görsellik\nVer hiç çocuk ne olsa\nVer hiç çift ne olsa\nGeçişt az olsa\nGeçiş daha az olsa\nGeçiş hiç olmasa da\n\nÇıkışta direnmek vardır\nÇıkışta sessiz ağlama vardır\nÇıkışta taşlaştırılan aş vardır\nÇıkışta yalvarma vardır\nÇıkışta isyan vardır\nÇıkışta teslim olma vardır\nÇıkışta ümitsizlik vardır\nÇıkışta köprünün başın çağlayan su\n\nKöprüden Önce Son Çıkış\nKöprüden Oncesi Son Çıkış\nKöprüde değildi\nKöprüyden Sonrası\nKöprüye yakın\nKöprüye uzak\nKöprüye bel bağlayan\nKöprüye atan\nKöprüye kalan\nKöprüy geçen\nKöprüye dönmeyen\n\n\nBilirdim umudu\nBilirdim olacakları\nBilirdim başını kaldırması\nBilirdim ölen\nBilirdim yaşanan\nBilirdim kahramanı\nBilirdim yenileni\nBilirdim acısını\nBilirdim sesini\nBilirdim kalben\nBilirdim çiftlik çarıklı\nBilirdim görenin tanısını\nBilirdim tanıdığı büyüklüğünü\n\nYa değildi artık\nYa kalmadı artık\nYa başında tavukçu saç\nYa başında saç yok\nYa başında yaşlı elleri\nYa hareket yok\nYa sesiz\nYa kelime yok\nYa vuku yok\n\nKöprü Önce Son Çıkış\nKöprüsüz çıkışmı\nÇıkışmız Köprüsüz mi\nEvet\nHayır\nBilmem\nBiliyordum\nÖğreniyorum\nÖğrendim\nYüreğimde\nSesal tütüyor\nAteş yaktı\nKül aldı\nKül açı\nAçıdan hiç kurtulmama\nKöprüden Önce Sön Çıkış\nÖlüm Öncesi Çıkış\nYasın Hızlığı\nCi Acısının Uzunluğu\nÖmer Yaman\'ın\'Un Karısı\nKapadokya\'nın Kızı\nEndülüs\'ün Seseri\nFellah\'ın Torunu\nAz Değerinden\nBu Çıkış', tags = ARRAY['Köprü', 'Veda', 'Ayrılık'] WHERE id = 36;

-- 62. Dil Gurbeti (Yaşar) - ÇOK UZUN
UPDATE literary_works SET content = E'Dil Gurbeti\nYaşar\n\nGurbette olmaktan çok çeşitli tanımlar dernen vardır. Biri şudur: yurdum dışında bulunmak. Lakin dilin gurbeti ayrı bir şeyin tanımıdır ki; bu belki de en ağır gurbettir.\n\nDili geçmiş insanların çoğu zaman ne yazık ki en büyük günah olarak görürdü bunu. İnsan kendi dilinde konuşamasa ne olur? Dilini kaybetse ne olur?\n\nMütekellim olmakça gelince, dilin gurbeti çok daha derindi. Tanrı\'nın harika bir hediyesi ve insana tanınan muazzam bir yetkinin elden gitmesi demektir bu.\n\nSesin gurbeti: Konuşmakta zorlanmak.\nDilin gurbeti: İçinde unuttuklarını anlatmakta zorlanmak.\nRuhun gurbeti: Ruhunu ifade edememek.\nHayatın gurbeti: Belki de bütün bunların kendisidir.\nBu gurbetler içinde birbirlerini beslerler, birbirlerini kenetlerler, birbirlerini yaşarlar.\n\nBu yazı türkçe yazılmış fakat anlamı belki de daha geniş. Dil sadece sözcükler değil. Dil, tarihin katedralidir. Dil, medeniyetin kalbidir. Dil, insanın ruhudur.\n\nO dilinin sesi artık yabancı geliyorsa, o dilinde bir harf hatırlayamamışsa, o dilinden sıkıntı çekiyorsa; işte o insan belki de en ağır gurbeti yaşıyor demektir.\n\nŞimdi sorusu bu: Dilini kaybeden, kendini de kaybetmiş midir? Belki de evet.\n\nBirbirine bağlanmış bir iki şey vardır:\nDil ve Kimlik\nDil ve Anı\nDil ve Ait Olmak\n\nGurbette kalabilmekle ve gurbette dilini kaybetmekle arasında ne kadar fark vardır?', tags = ARRAY['Dil', 'Kimlik', 'Gurbet'] WHERE id = 62;

-- 63. 24 Kasım (Zehra) - ÇOK UZUN
UPDATE literary_works SET content = E'24 Kasım - Kadın Günü\nZehra\n\nBirçok yıldır 24 Kasım Kadın Günü olarak kutlanmış. Bu gün her yılın gelmesi kadınları sevindirir, onlara değer verildiğini hatırlatır. Fakat bu yazı yazılırken; kendime sormak istiyorum: Acaba bir gün yeterli mi?\n\nKadın olmak başlı başına bir mücadeledir. Hayatın her alanında, her gün karşılaştığımız zorluklar, baskılar ve sorumluluklar vardır. Bütün bunları taşırken, bir de haksızlıklara uğramız çok sık.\n\nÖyle ki; kadına verilen haklar, erkekten geç gelmiştir. Eğitim, çalışma, seçme, seçilme... Tüm bu haklar kadın için bir mücadelenin ürünü.\n\nBu gün, bütün kadınları kutlamaktan da ziyade, onları desteklemek ve onların yanında olmak gerekir. Çünkü kadın günü sadece bu gün değil, her gün olmalıdır.\n\nKadının gücü, zerafeti, bilgeliği ve merhameti; dünyaya gerçek anlamda katkı sağlar. Bu yüzden kadınlar sadece kutlanmalı değil, her daim değer verilmeli ve desteklenmelidir.\n\n24 Kasım geçip gitse de; kadın mücadelesi devam ediyor. Ve işte o zaman, asıl İnsan Günü\'nün gelişi gerekiyor.', tags = ARRAY['Kadın', 'Hak', 'İnsan Hakları'] WHERE id = 63;

-- 64. Ben Yusuf Kuyudayım (H.T) - ÇOK UZUN
UPDATE literary_works SET content = E'Ben Yusuf Kuyudayım\nH.T\n\nZaman bitmek bilmiyor.\nYıllar senenin ardı sırasında akıp gitmiş.\nAma benim için; dipteki karanlığın derinliği aynı kalmış.\n\nHer gün yeniden yapılıyor benlik. Her gün yeniden hareket başlıyor.\nBilmiyorum umut diye bir şey vardır mı?\nBilmiyorum çıkış diye bir şey vardır mı?\nBilmiyorum bir gün güneş görecek miyiz?\n\nCevaplar bekliyorum.\nKimden mi? Don hiç bilmiyorum.\nBelki de sorunun cevabı soruda saklı.\nBelki de çıkış, bu kuyuda kalma çevre biliş.\n\nYusuf\' un hikayesi bilir misin?\nMisır\'a satılmış, zindan\'da çürütülmüş.\nAma sonunda sal oldu.\nSonunda itibar buldu.\nSonunda aile toplandı.\n\nBelki Yusuf\'un hikayesi bizim hikayemizdir.\nBelki bu kuyu sınavımızın yerdir.\nBelki de sınav bitere çıkacağız.\nBence de çıkacağız.\nÇünkü her kuyunun ağzı vardır.\nHer karanlığın ötesinde ışık vardır.\n\nBen Yusuf kuyudayım.\nAma Yusuf gibi ben de çıkacağım.\nBen Yusuf duasını ediyorum.\nBen Yusuf duasıyla çıkacağım.\n\nAllah\'ım!\nEğer bu kuyuda sayılan varsa;\nEğer bu ıstıraptaki bir hikmeti varsa;\nEğer bu acının bir mübarek ucu varsa.\nBir gün çıkacağımı bilir misin?\n\nBir gün çıkacağız.\nBir gün güneş göreceğiz.\nBir gün yeniden yaşayacağız.\nBen Yusuf kuyudayım.\nAma çıkacağım.', tags = ARRAY['Yusuf', 'Umut', 'Zindanhaftaya'] WHERE id = 64;

-- 75. Uber\'den Etkili Bir Anı
UPDATE literary_works SET content = E'Bir Uber sürücüsü hikayesi\nŞirket adı ne olursa olsun, sürücü abi\nBenim işim sadece yer değiştirmek değil\nBazen vizyonu taşıyorum\nBazen geleceği anlatıyorum\nBazen geçmişin yükünü hafifletiyorum\n\nBir gün bir taksici bana sordu\n"Sen nereye gidiyorsun?"\nBu soruda taksinin adı yok\nBu soruda sadece "nereye?" var\nBirisinin yolun ortasında kalmaması için\nBirisinin yolda kaybolmaması için\nBirisinin hedefe ulaşması için\n\nŞirketin adı değişebilir\nArabanın modeli farklı olabilir\nAma sorusu aynı\nCevabı vermesi de ayni insani sorumluluğu taşır\n\nHer yolculukta bir hikaye vardır\nHer yolculukta bir insan vardır\nHer insan bir hikaye taşır\nBazen başında bazen sırtında\n\nBu yüzden sordum\nSordum duyan olmadı\nSordum kimse cevap vermedi\nAma sormuş olmak yeterli oldu', tags = ARRAY['Taksi', 'İnsan', 'Bağlantı'] WHERE id = 75;

-- 76. Vazgeçme!
UPDATE literary_works SET content = E'Vazgeçme\n\nHayatka rağmen\nZorluklar rağmen\nAcılar rağmen\nYalnızlık rağmen\n\nVazgeçme\nSen güçlüsün\nSen kuvvetlisin\nSen yapabilirsin\n\nBiliyorum çok ağır\nBiliyorum çok zor\nBiliyorum dayanılmaz\nAma sen dayanabilirsin\n\nTarih yok mu?\nTarihteki olanlar yok mu?\nLarihte yöneticiler yok mu?\nBilim yok mu?\nBia yok mu?\nBilim ve bilim adamları yok mu?\n\nHepsinde ortak olan ne?\nHepsinde vazgeçmemiş olmak\n\nSen de vazgeçme\nSen de devam et\nSen de çık\nSen de yüksel\nSen de başar ol\n\nVazgeçme', tags = ARRAY['Umut', 'Cesarert', 'Israr'] WHERE id = 76;

-- 77. Gönül Yolu!
UPDATE literary_works SET content = E'Gönül Yolu!\n\nGönül yolunun sonunda ne vardır?\nBelki hoşlandığın insan\nBelki onu sahibinin yüzü\nBelki de sonuçsuzluk\n\nGönül yolu uzun mu?\nKimisi kısa sayar\nKimisi ise bütün hayat boyunca yürür\n\nGönül yolunda nasıl yürünür?\nBazen coşkuyla\nBazen çekinerek\nBazen sessizlikle\nBazen isyana karışmış halde\n\nGönül yolunun sonu mutluluğun başı mıdır?\nBelki\nBelki de öyle değil\nBelki gönül yolu bitmez\nBelki de hep yürüsmek vardır\n\nAma bir şey vardır ki kesin\nGönül yolunun her adımında hayat vardır\nHer nefesinde aşk vardır\nHer duasında umut vardır\n\nGönül yolundaki insan hiç yalnız değil\nÇünkü yüreği ona yol gösteriyor\nDuası onu destekliyor\nUmudu ona cesaret veriyor\n\nGönül Yolu!\nBenim de yollarımdan biri\nBenim de duasının malı\nBenim de yüreğimin ışığı\nGönül Yolu!', tags = ARRAY['Aşk', 'Gönül', 'Yol'] WHERE id = 77;

-- 78. Cuma Günü Nur Gibi
UPDATE literary_works SET content = E'Cuma Günü Nur Gibi\n\nCuma günü\nNur gibi bir vasi yayılır\nAcılar hafif düşer\nUmutlar yükselir\n\nCuma günü\nEzanın sesi yüreği teskin eder\nKalb atışları huzurlu olur\nCinanlar Allah\'a yönelir\n\nCuma günü\nNur gibi bir rahmet \nYeryüzüne inmişçesine\nBarışa çağrıyor\nBirliğe davet ediyor\nİnsanlara yol gösteriyor\n\nCuma günü\nCıllı ve Rahmet sözlerini düşün\n"Cuma günü sakaresine doymayacak nur akar"\nBu nur yeryüzüne değer\nBu nur kalplere değer\nBu nur hayata değer\n\nCuma günü\nHer mümin emini emini\nOnu hatırlarız\nOnu ağnız\nOnun güzelliğini duyarız\n\nCuma günü\nNur gibi\nNur gibibir huzur\nNur gibi bir barış\nNur gibi bir umut\nNur gibi bir aşk\n\nCuma günü\nNur gibi...\n\nAllah hepimizi bu nurun altında topladığı için şükürler olsun.', tags = ARRAY['Cuma', 'Nur', 'Huzur'] WHERE id = 78;

-- 94. Tefekkür-Terapi (Frau Isik) - ÇOK UZUN
UPDATE literary_works SET content = E'Tefekkür ve Terapi\nFrau Isik\n\nBazen kendimizi çok kötü hissettiğimiz anlar gelir.\nBazen hayattan soğuduk.\nBazen her şeyi saçma görüyoruz.\nBazen ortamın içinde seslersizce oturuyoruz.\nBazen hiçbir şeyin değeri kalır mı diye soruyoruz.\nBazen \\'sana ne\\'ye hazırlanıyoruz.\nBazen insan ömrüne dair yazıp çizmek istiyoruz bir süredir.\nBazen bu çaba boş gelmektedir.\nBazen biz burada ne yapmaktayız diye soruyoruz.\n\nÖyle anlar vardır ki; dış dünya çok boş görünür.\nÖyle anlar vardır ki; insan çok yalnız hisseder.\nÖyle anlar vardır ki; hiçbir şey anlam ifade etmez.\nÖyle anlar vardır ki; bir çıkış kapısı aranır.\n\nİşte tam bu anlarda birkaç şey yapabiliriz.\nBirincisi: Kendimize,haklı olmayı vermeliyiz.\nNerede olduğumuzda, nasıl hissets biliyor olduğumuzda.\nKendi sorularına kendi cevapları aramalıyız.\n\nSonrada:\nBir başka şey vardır ki, saçılınmış kuru taşların arasında;\nFarklı bir üzüm da vardır.\nFarklı bir çiçek vardır.\nFarklı bir kıl vardır.\nBunu görmek cidden zor.\nAma onu görmek yapılabilir. \n\nÖzel birisinin bir gülümsemesi\nBilmiş birinin bir sözü\nBilmemiş birinin bir tevazusu\nBir kuşun şarkısı\nBir çiçeğin açılması\nBir çocuğun masumiyeti\nBir annenin sevgisi\nBir babanın güvenliği\nBir Peygamberin hadisi\nBir düşün hayali\nBir dua sözcüğü\nBir dergâhın kapısı\nBir tekke de beklemek\nBir meşe ağacının solukluğu\nBir nehrin sesi\nBir dağın huzuru\nBir göğün derinliği\n\nHepsinde bir tefekkür vardır.\nHepsinde bir terapi vardır.\nHepsinde insanı çok uzak ve çok yakın hissettirme gücü vardır.\nBazen de bunu tedaviye çok benzetirim.\nBazen de bunun tedavi olduğunu söylerim.\n\nTek şart vardır:\nBilmek isteme\nUnutabilme\nBazen sessiz kalabilme\nBazen dinleyebilme\nBazen görülmeme kabullenebilme\nBazen kısırlık kabullenebilme\nBazen susabilme\n\nVe evet, bulunabilir.\nbulunur.\nBulunacaktır.\n\nTefekkür-Terapi\nSonsuza dek devam edecek bir şifaydır.', tags = ARRAY['Tefekkür', 'Terapi', 'Ilac'] WHERE id = 94;

-- 95. Bakmak ile Görmek (DeutschlandCompass)
UPDATE literary_works SET content = E'Bakmak ile Görmek\nDeutschlandCompass\n\nGöz açmak ile görmek farklı şeydir.\nBakmak ile görmek farklı şeydir.\nElmek açık olmak ile görmek açık olmak farklı şeydir.\n\nHayat çoğunlukla bakmadan ödün verir.\nÖyle çok bakmakla geçer hayatımız.\nHayat öyle çok bakmakla bitiverir.\n\nAma görmek başka bir şeydir.\nGörmek olmak kalıbı kırarak\nGörmek yeni camlar açmaktır.\nGörmek yeni ufuklar açmaktır.\nGörmek yeni hikaye başlatmaktır.\n\nBir çocuğun gözlerine bak.\nSonra da onu birkaç sene sonra gör.\nFark vardır mı?\nHer şey hızlı değişir mi?\nKimliğimiz değişir mi?\nUmudumuz değişir mi?\n\nBakmak dış dünyaya bakan basit bir harekettir.\nGörmek ise içe dönüş, derinleşme ve anlama çabası gösterir.\n\nBakmak: Gözü açmak\nGörmek: Kalbi açmak\nBakmak: Yüzeysel\nGörmek: Derinlikli\nBakmak: Hızlı\nGörmek: Zamana saygı\n\nBakmak ile görmek arasında belki de hayatın bütün farkı vardır.\nÖzelden bahsedersek;\nBakmak ile görmek arasında\nSevmek ile çıkar arasında\nHavlamak ile dinlemek arasında\nKavga ile diyalog arasında\nHayat ile ölüm arasında\n\nHer gün seç.\nHer gün karar ver.\nHer gün bak;\nveya gör.\nSeçimin tarafını bil.\n\nBakmak ile Görmek\nVar mı hiç fark?', tags = ARRAY['Görü', 'Bakış', 'Fark'] WHERE id = 95;

-- 96. Kediler (Frau Isik) - ÇOK UZUN
UPDATE literary_works SET content = E'Kediler\nFrau Isik\n\nKediler çok tuhaf canlılar.\nHer zaman kenardadırlar.\nHer zaman seçicidir.\nHer zaman efendisi olmayan kedi olur.\nHer zaman gitmek istiyorlardır.\nHer zaman dönüş\n\nKediler biz insanların çok tanımında.\nBazen bize zıt\nBazen bize benzer\n\nKediler; sakin göründüğü halde sürekli hareketlidir.\nKediler; sessiz olduğu halde çok ifadesidir.\nKediler; müstakil davranıyor gibi göründüğü halde çok bağlanmış olabilir.\nKediler; kültürel olmasa bile yaşadığı kültürün parçasıdır.\nKediler; çoğu zaman yalnız olsa da hiçbir zaman yalnız değildir.\n\nKediler ve Yalnızlık;\nYalnızlık bir duygudur\nSessizlik bir sünettir\nKediler; ilginç bir kimliğe sahiptir\n\nKediler ve Alışkanlık;\nHabitata alışması\nİnsana alışması\nYaşamaya alışması\nBu alışmanın bir bedeli vardır\nAlışmanın bedeli özgürlüktür\n\nKediler ve Duygu;\nKediyi görmek\nKedinin gözlerine bakmak\nKedinin dili dinlemek\nKedinin hareketi seyretmek\nHer birisi bir mesaj taşır\nHer birisi bir duygu ifade eder\n\nKediler ve Aşk;\nKedi sevmek\nKedinin sevgisini almak\nBu ikisinin arasında kocaman bir mesafe vardır\nKedi kendi sevgisini dağıtır\nBir insan kedi sevgisini isterken\nKedi kendi sevgisini verir\nİnsan ve kedi arasındaki ilişki birbiri tarafından anlaşılmayandır\nAma yine de vardır\n\nKediler ve Dokunuş;\nKediye dokunmak\nKedinin dokunuşu hissetmek\nKedinin tırnakları\nKedinin dişleri\nKedinin kürkleri\nHepsinde biz vardır\nHepsinde kedi vardır\nHepsinde ilişki vardır\n\nKediler ve Hüzün;\nKedi hüzünlü olabilir mi?\nKedi yalnız olabilir mi?\nKedi mutlu olabilir mi?\nKedi her şey olabilir\nBelki de insan kadar derin duygusu vardır\nBelki de sessizliğinde müziği vardır\nBelki de hareketsizliğinde şiir vardır\n\nKediler\nBazen felsefeci\nBazen sır taşıyıcı\nBazen yalnız yolcu\nBazen ev halkı\nBazen tane şair\nBazen dostumuz\nBazen ayna\n\nKediler dış dünyada mitolojiye, edebiyata, sanata malzeme olmuştur.\nKediler içinde dünyada; hiçbir zaman tam olarak anlaşılamayan bir varlık kalmıştır.\nKediler; belki insan olmamızın bize hatırlatan en iyi yöntemidir.\n\nBelki insanlar da kediler gibi tuhaftır.\nBelki insanlar da kediler gibi sessizdir.\nBelki insanlar da kediler gibi seçicidir.\nBelki insanlar da kediler gibi gitmek istiyorlardır.\nBelki insanlar da kediler gibi dönüş görevlidir.\nBelki insanlar da kediler gibi anlaşılmaz.\nBelki kediler bize bakıyor\nBelki biz kedilere bakıyoruz\nBelki ikiside birbirini görmüyor\nBelki ikiside birbirini anlıyor\n\nKediler\nBelki kedi olmakta benzetişide vardır.\nBelki ölmek kadar ölüme benzer sessizlik vardır.\nBelki de yokluk vardır.\nBelki de yoğunluk vardır.\nBelki de biz kediyi düşünerek kendimizi düşünüyoruz.\n\nKediler', tags = ARRAY['Kedi', 'Evcilleşme', 'Felsefe'] WHERE id = 96;

-- Kontrol
SELECT COUNT(*) as "güncellenen" FROM literary_works WHERE id IN (81,82,83,79,80,87,88,90,56,55,36,62,63,64,75,76,77,78,94,95,96);
